[workspace]
members = [
  "crates/*", 
  "docs/src/wasm", 
  "tests-integration", 
  "tests-package-set",
]
default-members = ["crates/*", "tests-integration"]
resolver = "1"

[profile.dev.package.insta]
opt-level = 3
