[package]
name = "lexing"
version = "0.1.0"
edition = "2024"

[dependencies]
syntax = { version = "0.1.0", path = "../syntax" }
unicode_categories = "0.1.1"

[dev-dependencies]
insta = "1.45.1"
test_each_file = "0.3.6"

