[package]
name = "lexing_new"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
memchr = "2.7.4"
syntax = { version = "0.1.0", path = "../syntax" }
unicode_categories = "0.1.1"

[dev-dependencies]
insta = "1.41.1"
test_each_file = "0.3.4"

