[package]
name = "parsing"
version = "0.1.0"
edition = "2021"

[dependencies]
drop_bomb = "0.1.5"
lexing = { version = "0.1.0", path = "../lexing" }
position = { version = "0.1.0", path = "../position" }
rowan = "0.16.1"
syntax = { version = "0.1.0", path = "../syntax" }

[dev-dependencies]
insta = "1.41.1"
test_each_file = "0.3.4"
